- name: install debian security updates
  hosts: myhosts
  sudo: yes
  vars:
     repo_description_file: /tmp/security.list
  tasks:
     - name: copy security repo description
       copy: src=playbooks/files/security.list dest={{repo_description_file}}
       register: copy_result
     - name: ensure aptitude is installed
       apt: name=aptitude state=present
       register: aptitude_install_result
     - name: update package list
       shell: aptitude update -o Dir::Etc::SourceList="{{repo_description_file}}"
       when: copy_result|success
       when: aptitude_install_result|success
       register: aptitude_update_result
     - name: delete security repo description
       shell: rm -rf {{repo_description_file}}
       when: copy_result|success
     - name: install security updates
       shell: aptitude upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
       when: aptitude_update_result|success
